import os

docs_dir = r'c:\Users\Lenovo\Desktop\EG\evergreen-ai-os\_opensquad\_memory\banco_ideias\docs'

docs = {
    'hub-chat-dispatcher.md': '# Hub: chat = dispatcher\n\n**Id:** hub-chat-dispatcher\n**Categoria:** Cockpit\n\n## O que é\nUma interface de chat omnipresente no Dashboard que atua como a interface humana direta para o Dispatcher subjacente.\n\n## Detalhe da Absorção\nEm vez de invocar comandos de CLI no terminal (`npm run start squad`), o usuário conversa no Hub. O chat entende a intenção, formata o payload (JSON) e deposita na Inbox correta do squad via Dispatcher. É a costura final para que o Cockpit seja operável por não-desenvolvedores.\n',
    
    'tag-ativacao.md': '# Tag de Ativação / Gatilho de Desenvolvimento\n\n**Id:** tag-ativacao\n**Categoria:** Cockpit\n\n## O que é\nUm evento visual e sistêmico disparado ao mover um card no Kanban ou via aprovação humana (HITL).\n\n## Detalhe da Absorção\nQuando uma ideia atinge o status "pronto p/ desenvolver", um gatilho é acionado. Se o Hub Chat estiver ativo, ele avisa o Dispatcher para rodar o Squad de Engenharia. A regra é rígida: o disparo sempre exige aprovação humana, barrando a IA de sair programando ou enviando e-mails sem consentimento.\n',
    
    'multi-plataforma-freelance.md': '# Captação multi-plataforma de propostas\n\n**Id:** multi-plataforma-freelance\n**Categoria:** Feature\n\n## O que é\nUma ferramenta de ingestão de oportunidades de plataformas como Upwork, Malt e Contra para o pipeline de vendas da agência.\n\n## Detalhe da Absorção\nA Fase 1 é semi-manual (colar URL no dashboard para contornar bloqueios de scraper). A Fase 2 envolve usar o n8n ou Zapier lendo RSS feeds de buscas salvas do Upwork e batendo em um Webhook do Opensquad, populando o Kommo CRM automaticamente com leads quentes.\n',
    
    'log-audio-wpp.md': '# Log de áudio via WhatsApp\n\n**Id:** log-audio-wpp\n**Categoria:** Feature\n\n## O que é\nInterface de voz sem atrito para os colaboradores (Closer, Account Manager) atualizarem o sistema.\n\n## Detalhe da Absorção\nO colaborador manda um áudio de 2 minutos no WhatsApp da IA após uma reunião. O sistema transcreve via Whisper, identifica o cliente pelo contexto semântico, resume os próximos passos e injeta a anotação diretamente no ClickUp e no Kommo CRM, dispensando o trabalho braçal de data-entry.\n',
    
    'sla-watchdog.md': '# SLA Watchdog (WhatsApp)\n\n**Id:** sla-watchdog\n**Categoria:** Feature\n\n## O que é\nUm cão de guarda automatizado que garante o tempo de resposta em grupos de WhatsApp com clientes.\n\n## Detalhe da Absorção\nO agente lê passivamente os grupos via Evolution API. Se o cliente manda uma mensagem e nenhum humano da equipe responde dentro da janela de SLA (ex: 30 minutos em horário comercial), o bot dispara um alerta no Slack/WhatsApp interno para os diretores.\n',
    
    'esteira-onboarding.md': '# Esteira de Onboarding Automatizada\n\n**Id:** esteira-onboarding\n**Categoria:** Feature\n\n## O que é\nA materialização prática do `squad-onboarding`.\n\n## Detalhe da Absorção\nQuando um negócio é ganho, a esteira executa chamadas em cadeia: cria o Workspace no ClickUp a partir de um template, gera os DoDs, cria a pasta isolada no Google Drive do cliente, convida os e-mails e redige o e-mail de boas-vindas com todos os links. O humano apenas revisa e envia.\n',
    
    'dossie-provas.md': '# Dossiê de Provas de Confiança\n\n**Id:** dossie-provas\n**Categoria:** Feature\n\n## O que é\nUm agente focado na construção de autoridade (Case Studies) automatizada.\n\n## Detalhe da Absorção\nO agente varre o GA4 e o Meta Ads dos clientes semanalmente. Encontrando anomalias positivas (ex: ROAS subiu 40%), ele tira "prints" de dados, gera um mini-relatório do que foi feito e joga no Banco do Vector Store. Isso é consumido pela criação de propostas futuras para clientes do mesmo nicho.\n',
    
    'health-score.md': '# Health Score por Dados\n\n**Id:** health-score\n**Categoria:** Feature\n\n## O que é\nUm índice matemático de risco de churn baseado em comportamento frio, não apenas em intuição do gerente de conta.\n\n## Detalhe da Absorção\nCruza a frequência de contato no WhatsApp/e-mail com a performance das campanhas. Se o CPA sobe mais de 20% e há 15 dias sem reunião registrada com o cliente, a IA gera preventivamente uma tarefa "Alerta de Risco: Call de Alinhamento Urgente" no ClickUp dos diretores.\n',
    
    'icebreaker.md': '# Icebreaker de Prospecção\n\n**Id:** icebreaker\n**Categoria:** Feature\n\n## O que é\nUma feature do `squad-prospector` que abandona o modelo de "e-mail frio genérico" a favor da entrega de valor instantânea.\n\n## Detalhe da Absorção\nVarre o site ou LinkedIn do lead usando um scraper headless. Roda um mini "Raio-X" (vê se o site tá lento, se o pixel tá faltando, se a copy da Hero Section é fraca) e inicia a prospecção não pedindo uma call, mas entregando a análise de graça como gancho de autoridade.\n',
    
    'maquina-completa.md': '# Máquina Completa (upsell de infra)\n\n**Id:** maquina-completa\n**Categoria:** Commercial\n\n## O que é\nNossa tese central de vendas. Não vendemos gestão de tráfego, vendemos arquitetura de vendas.\n\n## Detalhe da Absorção\nNo discurso comercial, o produto final é a infraestrutura montada (Anúncio -> WhatsApp com IA qualificador -> Reunião agendada no Kommo). Vender o ecossistema reduz churn porque o cliente percebe que está comprando uma máquina corporativa operada pela agência, e não um freela que clica botões no Facebook Ads.\n',
    
    'loop-pos-call.md': '# Loop de retroalimentação pós-call\n\n**Id:** loop-pos-call\n**Categoria:** Feature\n\n## O que é\nA automatização da inteligência de vendas após o término de um pitch de fechamento.\n\n## Detalhe da Absorção\nOuve a transcrição da reunião final, extrai o frame SPICED (Situação, Dor, Impacto, Evento Crítico, Decisão), atualiza o card no Kommo e joga objeções não contornadas no RAG para que os roteiros de anúncios sejam atualizados e rebatam a objeção no top-funil.\n',
    
    'pesquisa-academica.md': '# Pesquisa acadêmica aplicada\n\n**Id:** pesquisa-academica\n**Categoria:** Service\n\n## O que é\nNosso fosso competitivo (moat) em relação a agências tradicionais. Traduzir paper gringo em dinheiro para o cliente.\n\n## Detalhe da Absorção\nAcompanhamos papers sobre Mixture of Experts, Ensembling e RAG e os aplicamos nas ferramentas do cliente. Enquanto o mercado discute como usar o ChatGPT, nós vendemos o conceito de arquiteturas auto-corretivas aplicadas à performance comercial do cliente.\n',
    
    'forward-deployed.md': '# Forward Deployed AI\n\n**Id:** forward-deployed\n**Categoria:** Service\n\n## O que é\nUma modalidade de serviço High-Ticket para clientes corporativos com paranoia de privacidade (Saúde, Finanças, Jurídico).\n\n## Detalhe da Absorção\nEm vez de rodar a inteligência nos nossos servidores batendo na OpenAI, instalamos o sistema dentro da AWS/GCP do cliente rodando modelos Open-Source (Llama, Mistral) on-premise. Toda a IA roda na infraestrutura deles. DNA inspirado em modelos da Palantir.\n',
    
    'cockpit-produto.md': '# Cockpit interno → produto\n\n**Id:** cockpit-produto\n**Categoria:** Service\n\n## O que é\nA expansão da Evergreen AI OS para além de uma agência de serviços: tornar-se uma empresa de SaaS.\n\n## Detalhe da Absorção\nApós rodar e provar o valor do Dashboard Interno (Cockpit) conosco, empacotamos o sistema e vendemos licenças para outras agências ou consultorias gerirem suas próprias operações com a nossa arquitetura de squads. Pivot para receita recorrente pura (MRR).\n',
    
    'precificacao-valor.md': '# Precificação por valor/eficiência\n\n**Id:** precificacao-valor\n**Categoria:** Commercial\n\n## O que é\nA substituição radical do modelo de "Hora/Homem" das agências clássicas.\n\n## Detalhe da Absorção\nSe a IA reduz a redação de uma proposta de 4 horas para 4 minutos, cobrar por hora destrói o nosso lucro. Cobra-se um Setup Fee alto (instalação da infra) + um Fee de Estratégia e Mídia. A eficiência ganha pela máquina aumenta a margem bruta da Evergreen, e não barateia o projeto para o cliente.\n',
    
    'service-as-software.md': '# Service-as-a-Software (oferta invisível)\n\n**Id:** service-as-software\n**Categoria:** Commercial\n\n## O que é\nA apresentação do nosso modelo de Growth para o mercado.\n\n## Detalhe da Absorção\nVende-se previsibilidade de crescimento, não "robôs de IA". A tecnologia complexa e os agentes atuam nos bastidores (invisíveis), para que o cliente pague por resultados corporativos em vez de ficar microgerenciando a ferramenta.\n',
    
    'ai-cmo-mrr.md': '# AI-CMO como justificativa de MRR\n\n**Id:** ai-cmo-mrr\n**Categoria:** Commercial\n\n## O que é\nO argumento para ancorar a retenção contínua (Mensalidade/Fee) dos clientes.\n\n## Detalhe da Absorção\nNão cobramos manutenção de ferramenta. O Fee mensal compra o acesso contínuo ao "Cérebro Estratégico" (AI-CMO) da agência, que lê dados diariamente, propõe testes A/B, analisa relatórios de concorrência e gera insights estratégicos todo mês de forma ativa.\n',
    
    'dogfooding.md': '# Dogfooding\n\n**Id:** dogfooding\n**Categoria:** Commercial\n\n## O que é\nO princípio inegociável de que a Evergreen consome o próprio veneno (Eat your own dog food).\n\n## Detalhe da Absorção\nSe vamos vender automação de prospecção e agentes qualificadores para clientes, toda a operação comercial e de atendimento da nossa agência precisa rodar 100% sobre o Evergreen AI OS. Os gargalos devem ser sentidos e consertados por nós antes de serem vendidos.\n',
    
    'fabrica-back-front.md': '# Fábrica: backoffice vs. frontoffice\n\n**Id:** fabrica-back-front\n**Categoria:** Commercial\n\n## O que é\nA divisão do trabalho na nova era das agências. Onde alocamos esforço humano vs. esforço de silício.\n\n## Detalhe da Absorção\nTodo o Backoffice (criação de projetos no ClickUp, redação de contratos, preenchimento de CRM, confecção burocrática de relatórios) é 100% tratorado por IA. O humano é realocado 100% para o Frontoffice: julgamento crítico, reuniões de relacionamento, negociação e estratégia visual.\n',
    
    'change-management.md': '# Change Management no cliente\n\n**Id:** change-management\n**Categoria:** Service\n\n## O que é\nUm playbook de segurança psicológica para equipes de clientes que sofrem pânico de serem substituídas por IA.\n\n## Detalhe da Absorção\nFrequentemente a equipe do cliente sabota a implantação da ferramenta. O processo de Change Management treina o funcionário do cliente, mostrando que a IA tira o trabalho repetitivo, dando a ele o poder de gerenciar a máquina. A meta é que o funcionário promova a ferramenta, reduzindo o churn de software por boicote humano.\n',
    
    'auditoria-ai-first.md': '# Auditoria de Prontidão AI-First\n\n**Id:** auditoria-ai-first\n**Categoria:** Service\n\n## O que é\nUm serviço consultivo de entrada (Front-End) para diagnosticar se a empresa do lead está pronta para IA.\n\n## Detalhe da Absorção\nAudita a organização em 7 dimensões (Qualidade dos Dados, Cultura, Processos Mapeados, Ferramentas, Segurança, etc). Gera um score final e um plano de ataque de 6 meses ("AI-Firstify"). Pode ser cobrado como produto isolado High-Ticket ou servir de isca para o serviço contínuo.\n',
    
    'prospec-wpp-evolution.md': '# Prospecção WhatsApp (Evolution API)\n\n**Id:** prospec-wpp-evolution\n**Categoria:** Feature\n\n## O que é\nA arquitetura técnica para realizar outbound via WhatsApp de forma viável.\n\n## Detalhe da Absorção\nA API Oficial da Meta é proibitiva para disparo frio devido ao custo e risco de banimento de Business Managers oficiais. Utilizamos a Evolution API (não-oficial via leitura de QR Code) hospedada em VPS própria, operando um fleet de chips aquecidos para iniciar a conversa, movendo para o oficial apenas quando o lead demonstra interesse (Inbound).\n',
    
    'voip-qualificacao.md': '# VoIP inteligente de qualificação\n\n**Id:** voip-qualificacao\n**Categoria:** Service\n\n## O que é\nA evolução do SDR humano. Um agente autônomo baseado em voz que liga ativamente para os leads.\n\n## Detalhe da Absorção\nIntegração de ElevenLabs (voz ultrarrealista com latência mínima) e Twilio (telefonia). O agente liga para leads de formulário em menos de 5 minutos, faz o filtro BANT (Budget, Authority, Need, Timing) conversando naturalmente, e se qualificado, envia um link do Calendly para marcar com o Closer.\n',
    
    'ia-adapta-cliente.md': '# Princípio: IA se adapta ao cliente\n\n**Id:** ia-adapta-cliente\n**Categoria:** Commercial\n\n## O que é\nA regra máxima para não gerar fadiga de software nos clientes (Software Fatigue).\n\n## Detalhe da Absorção\nNão forçamos o cliente a entrar no nosso portal customizado para ver relatórios se ele detesta mudar de tela. Se ele vive no Slack, nossos agentes mandam o resumo no Slack dele. Se ele usa o Trello em vez do ClickUp, o MCP se adapta e atualiza o Trello dele. A inteligência artificial é injetada na infraestrutura legada do cliente, eliminando objeções na venda.\n',
    
    'idea-detail-edit.md': '# Editar ideias + ver detalhe / 1 doc por ideia\n\n**Id:** idea-detail-edit\n**Categoria:** Cockpit\n\n## O que é\nFuncionalidade crucial do dashboard de controle do Banco de Ideias.\n\n## Detalhe da Absorção\nO Kanban passou de uma leitura fria do JSON para um sistema modal robusto. Agora é possível não só ler o Documento detalhado em Markdown nativo, como interagir para mover conexões e editar descrições diretamente pela interface, consolidando o Cockpit como ponto único da verdade, substituindo a edição manual via IDE.\n',
    
    'banco-arquitetura-tab.md': '# Aba Banco de Arquitetura no dashboard\n\n**Id:** banco-arquitetura-tab\n**Categoria:** Cockpit\n\n## O que é\nA visibilidade da malha estrutural do sistema em ambiente UI.\n\n## Detalhe da Absorção\nAtualmente a arquitetura repousa num arquivo `.md` no backend. Esta ideia propõe uma aba dedicada no Dashboard, renderizando a árvore de Squads, MCPs e permissões. Serve para que diretores e arquitetos acompanhem visualmente a topologia e as capacidades reais do ecossistema, ajudando no onboarding de novos engenheiros.\n',
    
    'clients-clickup-sync.md': '# Carteira ↔ ClickUp (puxar pastas, sincronizar cards)\n\n**Id:** clients-clickup-sync\n**Categoria:** Feature\n\n## O que é\nO sincronizador bidirecional entre o Dashboard local (`clients/config.json`) e a realidade (ClickUp).\n\n## Detalhe da Absorção\nA aba "Carteira de Clientes" no dashboard compara as informações declarativas locais com as listas existentes na API do ClickUp. Havendo divergência, propõe a criação das pastas ou atualização dos cards. Opera estritamente com aprovação humana (Write/Read barrier), garantindo a integridade dos workspaces dos clientes.\n',
    
    'idea-bank-auto.md': '# Banco de Ideias auto-atualizável\n\n**Id:** idea-bank-auto\n**Categoria:** Cockpit\n\n## O que é\nAvanço do ciclo de vida das ideias, passando de humano-dependente para autônomo reativo.\n\n## Detalhe da Absorção\nUm Reconciliador lê a estrutura de pastas do projeto, status de cards no ClickUp e merges no GitHub. Se ele detecta que os scripts da ideia "tag-ativacao" existem e rodam na branch principal, ele move automaticamente o card do Kanban de "desenvolvimento" para "pronto". Reduz trabalho de manutenção.\n',
    
    'matriz-risco-comercial.md': '# Matriz de Risco Comercial (Lead Scoring)\n\n**Id:** matriz-risco-comercial\n**Categoria:** Commercial\n\n## O que é\nFramework estrito para impedir a agência de assumir clientes tóxicos ou não-escaláveis.\n\n## Detalhe da Absorção\nCruza Probabilidade de Sucesso Técnico x Severidade Operacional. Avalia via IA os inputs da prospecção: O nicho permite margem? O cliente tem maturidade digital? Se o score bate na zona de risco vermelha, o lead é desqualificado imediatamente (refugo automático), salvando o time de dor de cabeça futura.\n',
    
    'estrutura-modal-briefing.md': '# Estrutura Modal de Briefing\n\n**Id:** estrutura-modal-briefing\n**Categoria:** Feature\n\n## O que é\nA padronização sintética da entrega de relatórios e notificações feitas por Agentes para Humanos.\n\n## Detalhe da Absorção\nAgentes têm a tendência de ser verborrágicos (falar demais). Esta feature cria 3 modos rígidos via Prompt Engineering: "Daily" (pontos bala crus da operação), "Topic" (Deep dive sobre uma campanha ou problema), e "Incident" (Gatilho emergencial focado apenas na ação exigida do fundador).\n',
    
    'clickup-direct-injector.md': '# ClickUp Direct Injector (Client Insights)\n\n**Id:** clickup-direct-injector\n**Categoria:** Feature\n\n## O que é\nUma rodovia expressa para transformar relatórios de IA em itens acionáveis sem fricção.\n\n## Detalhe da Absorção\nEm vez de gerar um PDF para o analista ler, o squad analítico (após processar GA4 e encontrar um insight para anúncio) empurra esse insight diretamente para o ClickUp do cliente, como uma "Task" na lista "Backlog de Ideias do Cliente". Pula o banco da EG e vai direto para a esteira operacional do tráfego.\n'
}

for filename, content in docs.items():
    doc_file = os.path.join(docs_dir, filename)
    with open(doc_file, 'w', encoding='utf-8') as f:
        f.write(content)

print(f"Lote 3: Generated {len(docs)} files.")
