import os

docs_dir = r'c:\Users\Lenovo\Desktop\EG\evergreen-ai-os\_opensquad\_memory\banco_ideias\docs'

docs = {
    'squad-propostas.md': '# Squad de Propostas\n\n**Id:** squad-propostas\n**Categoria:** Squad\n\n## O que é\nO processo focado na conversão técnica e comercial. Recebe a oportunidade qualificada e avalia o fit com o nosso ICP antes de gerar o rascunho da proposta padrão da EG.\n\n## Detalhe da Absorção\nEste conceito foi **consolidado dentro do `squad-hunter` (Closer)**. A arquitetura determinou que não precisávamos de um squad isolado só para a proposta; em vez disso, o agente Closer, dentro do pipeline de vendas, assume a responsabilidade de redigir o documento consultando o Banco de Stack e o histórico de reuniões.\n',
    
    'squad-relatorios.md': '# Squad Relatórios de Cliente\n\n**Id:** squad-relatorios\n**Categoria:** Squad\n\n## O que é\nUm squad especializado em conectar-se às plataformas de mídia e CRM (Meta, Google Ads, Kommo) para extrair os dados e construir uma narrativa estratégica sobre a performance do cliente.\n\n## Detalhe da Absorção\nEm vez de montar dashboards engessados, este squad escreve a narrativa do que os números significam. Ele lê os dados brutos via MCPs (integrações seguras) e gera um report executivo que o BI então apenas exibe, poupando tempo de análise do gestor.\n',
    
    'squad-onboarding.md': '# Squad Onboarding / Kommo / ClickUp\n\n**Id:** squad-onboarding\n**Categoria:** Squad\n\n## O que é\nO time autônomo responsável pelo provisionamento da infraestrutura do cliente após o fechamento do contrato. \n\n## Detalhe da Absorção\nAssim que a proposta é dada como "Ganho" no Kommo, este squad assume. Ele cria as pastas do cliente no ClickUp, configura os campos customizados no CRM, e inicializa o `clients_config.json`. Já existe parcialmente sob a alcunha de `eg_setup`.\n',
    
    'squad-kickoff.md': '# Squad Kickoff Técnico\n\n**Id:** squad-kickoff\n**Categoria:** Squad\n\n## O que é\nO agente que atua no hiato entre a venda e a execução. Lê o escopo recém-aprovado e monta a árvore inicial de dependências técnicas.\n\n## Detalhe da Absorção\nEle gera as Tasks base no ClickUp e monta o esqueleto do repositório no GitHub para o time de desenvolvimento. Atenção arquitetural: há risco de overlap com o `squad-engenharia`, devendo atuar apenas no setup administrativo, delegando o design de software (SDD) para a engenharia.\n',
    
    'squad-raiox.md': '# Squad Raio-X Automatizado\n\n**Id:** squad-raiox\n**Categoria:** Squad\n\n## O que é\nA automação do nosso framework principal de auditoria comercial. Coleta os dados de um lead prospectado e diagnostica as três frentes do funil.\n\n## Detalhe da Absorção\nAnalisa Oferta (Copy/Página), Demanda (Tráfego/Mídia) e Conversão (CRM/Atendimento). Gera um score automático e o relatório de gargalo que será usado pelo Closer na reunião de vendas para ancorar a autoridade da agência.\n',
    
    'squad-criativos.md': '# Squad de Criativos\n\n**Id:** squad-criativos\n**Categoria:** Squad\n\n## O que é\nAgentes focados na ideação e roteirização da matéria-prima publicitária. Transforma a estratégia da conta em variações testáveis.\n\n## Detalhe da Absorção\nGera roteiros para VSLs, variações A/B de Copy para os anúncios e estruturas visuais. Ele consome o dossiê da marca no Vector Store para garantir aderência ao tom de voz do cliente.\n',
    
    'squad-trafego.md': '# Otimização de Tráfego (HITL)\n\n**Id:** squad-trafego\n**Categoria:** Squad\n\n## O que é\nMonitor de performance de mídia paga. Lê o gasto, o CPA e o ROAS em tempo real e sugere pausar campanhas perdedoras ou escalar as vencedoras.\n\n## Detalhe da Absorção\n**Princípio vital:** Nunca atua de forma 100% autônoma sobre a verba do cliente. Opera com *Write/Read barrier*, exigindo que um humano clique em "Aprovar Mudança" para que a API do Facebook/Google receba o comando.\n',
    
    'squad-seo-geo.md': '# Squad SEO / GEO\n\n**Id:** squad-seo-geo\n**Categoria:** Squad\n\n## O que é\nA força tarefa para Busca Orgânica (SEO tradicional) e Generative Engine Optimization (GEO — otimização para ser citado por LLMs como o ChatGPT).\n\n## Detalhe da Absorção\nAudita as propriedades do cliente, melhora a arquitetura de informação e injeta entidades semânticas legíveis por agentes de IA para garantir presença de marca nos novos motores de busca sintéticos.\n',
    
    'squad-voz-cliente.md': '# Squad de Voz do Cliente\n\n**Id:** squad-voz-cliente\n**Categoria:** Squad\n\n## O que é\nO esquadrão focado na retenção e qualidade do produto. Minera e categoriza feedbacks espalhados em múltiplas plataformas.\n\n## Detalhe da Absorção\nLê tickets de suporte, comentários em anúncios, e-mails e anotações do CRM. Agrupa temas, conta a frequência e elenca prioridades. Este material enriquece o Dossiê do Cliente e é jogado no Vector Store (RAG) para que o copywriter tenha a exata linguagem do público.\n',
    
    'segundo-cerebro.md': '# Segundo Cérebro integrado (AI OS)\n\n**Id:** segundo-cerebro\n**Categoria:** Infra\n\n## O que é\nA fundação conectiva de todo o Evergreen AI OS. Um LLM global com tentáculos nas nossas ferramentas corporativas, atuando como o oráculo da empresa.\n\n## Detalhe da Absorção\nPlugado no Google Drive, ClickUp, Kommo, transcrições de reuniões e base de propostas. A ideia é que em vez de um chatbot vazio, qualquer interação com o sistema opere sob um "Contexto 360º" em tempo real sobre a nossa operação.\n',
    
    'vector-store.md': '# Vector store EG (pgvector)\n\n**Id:** vector-store\n**Categoria:** Infra\n\n## O que é\nO banco de dados relacional e vetorial onde toda a nossa memória de longo prazo é armazenada e indexada por significado semântico.\n\n## Detalhe da Absorção\nConstruído sobre o PostgreSQL (pgvector). Armazena as propostas enviadas, os relatórios de Raio-X, transcrições e cases de sucesso. A função `rag_search(query, client_id)` garante isolamento para que o contexto de um cliente nunca vaze na geração de texto de outro.\n',
    
    'context-decay.md': '# Context Decay\n\n**Id:** context-decay\n**Categoria:** Infra\n\n## O que é\nUm princípio matemático aplicado ao RAG (Retrieval-Augmented Generation) para esquecer informações obsoletas.\n\n## Detalhe da Absorção\nToda entrada no Vector Store ganha um timestamp. Na hora da busca vetorial, o score de similaridade é multiplicado por um "peso de recência" (decay). Assim, metodologias antigas da agência são naturalmente substituídas pelas novas sem precisar que ninguém as delete.\n',
    
    'llm-agnostic.md': '# Camada LLM-agnostic\n\n**Id:** llm-agnostic\n**Categoria:** Infra\n\n## O que é\nA garantia de não sermos reféns da OpenAI ou da Anthropic. Toda a inteligência artificial do sistema passa por um roteador padronizado.\n\n## Detalhe da Absorção\nUtilizando um gateway (como LiteLLM ou OpenRouter), os agentes do Opensquad solicitam completions genéricas. Trocar o modelo base de todo o OS de GPT-4o para Claude 3.5 Sonnet é a mudança de uma única variável de ambiente.\n',
    
    'client-config-auto.md': '# Geração automática de client_config\n\n**Id:** client-config-auto\n**Categoria:** Infra\n\n## O que é\nA automatização da burocracia do onboarding de novos clientes no sistema.\n\n## Detalhe da Absorção\nQuando um cliente novo assina, o `squad-onboarding` ouve/lê a primeira reunião e preenche sozinho o arquivo `client_config.yaml` mapeando as URLs, chaves e IDs das plataformas daquele cliente. Porém, como regra de segurança, as configurações core do `evergreen-ai-os` permanecem sob controle manual.\n',
    
    'ensemble-juiz.md': '# Ensemble + Juiz (Mixture of Agents)\n\n**Id:** ensemble-juiz\n**Categoria:** Infra\n\n## O que é\nArquitetura de deliberação para tarefas críticas, usando múltiplos modelos menores competindo e um modelo grande julgando a melhor resposta.\n\n## Detalhe da Absorção\nEm cenários complexos (como fechar a arquitetura de um software de cliente no `squad-engenharia`), rodamos modelos baratos (ex: Llama 3) em paralelo (Ensemble) gerando várias propostas de solução. Um LLM premium atua como Juiz, lendo todas e sintetizando a decisão final. Aplicado apenas em etapas de alto ROI devido ao custo e latência.\n',
    
    'vibe-building.md': '# Vibe Building (blocos reutilizáveis)\n\n**Id:** vibe-building\n**Categoria:** Infra\n\n## O que é\nA estratégia de componentização do desenvolvimento das ferramentas do OS. Não criamos scripts monstruosos únicos, criamos pequenos legos lógicos.\n\n## Detalhe da Absorção\nBlocos funcionais (como o "qualificador de WhatsApp", o "leitor de GA4", a "auditoria de CRM") são instanciados e conectados via Dispatcher. Em vez de reescrever lógica, reaproveitamos os módulos. É o equivalente de ter componentes no frontend, mas aplicados à lógica de agentes.\n',
    
    'stack-memoria-zep.md': '# Segundo Cérebro — stack de memória (Zep)\n\n**Id:** stack-memoria-zep\n**Categoria:** Infra\n\n## O que é\nIntegração de um banco de retenção longa específico para LLMs, como o Zep, atuando acima do Vector Store primitivo.\n\n## Detalhe da Absorção\nFase 1.5 do RAG. Em vez de fazer buscas burras no pgvector, o Zep atua condensando e sumariando conversas passadas para manter o contexto dos clientes sempre rápido na memória curta dos agentes, otimizando o gasto de tokens e evitando esquecimento de detalhes cruciais.\n',
    
    'skill-brand-eg.md': '# Skill brand-guidelines-EG\n\n**Id:** skill-brand-eg\n**Categoria:** Infra\n\n## O que é\nA padronização estética obrigatória incorporada em um Skill reutilizável por qualquer squad.\n\n## Detalhe da Absorção\nGarante que todo artefato gerado (seja um dashboard no React, um PDF de proposta ou um doc Markdown) aplique a identidade visual da EG: paleta musgo/menta/baunilha, tipografia Helvetica Neue e o tom de voz "Boutique". É a evolução lógica do `eg_style.js` para um agente independente.\n',
    
    'skill-squad-creator.md': '# Skill squad-creator-EG\n\n**Id:** skill-squad-creator\n**Categoria:** Infra\n\n## O que é\nA formalização do processo de "nascer um novo squad" (Scaffolder) em uma skill padronizada do sistema.\n\n## Detalhe da Absorção\nLê o Banco de Arquitetura e gera automaticamente a estrutura de pastas, os arquivos `.agent.md`, as configurações e o `Definition of Done` (DoD) de um esquadrão nascente. Substitui a criação de arquivos na mão.\n',
    
    'eg-mcp-tools.md': '# eg-mcp-tools (MCP padronizado)\n\n**Id:** eg-mcp-tools\n**Categoria:** Infra\n\n## O que é\nA nossa própria coleção de Model Context Protocol (MCP) servers para interagir com o ecossistema SaaS da agência de forma segura.\n\n## Detalhe da Absorção\nDesenvolvimento de servidores MCP como o `clickup_writer`, `kommo_writer`, `ga4_reader`. Fundamental: eles possuem annotations rígidos de risco — `Write/Read barrier` — garantindo que os agentes não tenham permissão silenciosa de apagar coisas do CRM ou publicar sem aprovação humana.\n',
    
    'skill-raiox.md': '# Skill raio-x-skill\n\n**Id:** skill-raiox\n**Categoria:** Infra\n\n## O que é\nTransformação do relatório do Raio-X numa Skill portátil que pode ser invocada por outros esquadrões.\n\n## Detalhe da Absorção\nEm vez de ter um squad exclusivo, a função central de aplicar a auditoria nos 3 Pilares (Oferta/Demanda/Conversão) e gerar o scoring pode ser invocada como skill pelo `squad-prospector` (Top Funnel) ou pelo `squad-hunter` (Bottom Funnel) dependendo do nível de dados disponíveis do cliente.\n',
    
    'banks-portability.md': '# Portabilidade dos bancos (não ser refém do opensquad)\n\n**Id:** banks-portability\n**Categoria:** Infra\n\n## O que é\nA decisão arquitetural de não "casar" nossos dados e inteligência proprietária com o framework subjacente (Opensquad ou qualquer outro).\n\n## Detalhe da Absorção\nNossos bancos (Ideias, Stack, Arquitetura) devem permanecer sendo arquivos JSON/MD puramente portáveis e legíveis, talvez mudando do diretório interno `_opensquad/` para um top-level como `data/`. Mantemos o paradigma de usar arquivos em vez de Banco de Dados pesado (SQL) para facilitar a leitura crua por LLMs e o versionamento em Git.\n',
    
    'filosofia-visual-eg.md': '# Filosofia Visual EG (Manifesto de Design)\n\n**Id:** filosofia-visual-eg\n**Categoria:** Infra\n\n## O que é\nO documento de Ground Truth estético. O farol visual da EG, que traduz o feeling de marca premium para o design de software e peças publicitárias.\n\n## Detalhe da Absorção\nEstabelece regras rígidas (negative space, cores neutras vibrantes, ausência de ruído genérico). Serve como contexto vital a ser inserido no prompt de qualquer agente de engenharia de frontend ou gerador de imagem, blindando contra resultados visualmente medíocres (slop).\n',
    
    'web-artifacts-builder.md': '# Web Artifacts Builder (Motor de UI Rica)\n\n**Id:** web-artifacts-builder\n**Categoria:** Infra\n\n## O que é\nUm ecossistema técnico focado na geração rápida e belíssima de interfaces web (Landing Pages, Cockpits) liderado por IA.\n\n## Detalhe da Absorção\nUsa React/Vite/Tailwind amarrado a regras anti-slop ditadas pela Filosofia Visual EG. Permite que um Agente, ao invés de cuspir HTML sujo, monte componentes padronizados com aparência premium, ideal para protótipos de dashboards ou páginas de clientes em horas, não semanas.\n',
    
    'handoff-assincrono-inboxes.md': '# Arquitetura de Handoff Assíncrono (Inboxes)\n\n**Id:** handoff-assincrono-inboxes\n**Categoria:** Infra\n\n## O que é\nO padrão de comunicação interno primário do nosso ecossistema de esquadrões.\n\n## Detalhe da Absorção\nPara evitar o "spaghetti de agentes" se chamando diretamente e travando em timeouts, implementamos o padrão Pub/Sub via filesystem. Esquadrões gravam os seus outputs finais em diretórios "Inbox". O `Dispatcher` monitora as caixas de saída e roteia silenciosamente os artefatos para a caixa de entrada do próximo squad da esteira, garantindo desacoplamento robusto.\n'
}

for filename, content in docs.items():
    doc_file = os.path.join(docs_dir, filename)
    with open(doc_file, 'w', encoding='utf-8') as f:
        f.write(content)

print(f"Lote 2: Generated {len(docs)} files.")
